name: Build Wheels Batch

on: workflow_dispatch

permissions:
  contents: write
  
jobs:
  run_workflow_release:
    name: Build Wheels & Release
    strategy:
      max-parallel: 1
      matrix:
        version: ["v0.2.16", "v0.2.13", "v0.2.14", "v0.2.15"]
    uses: ./.github/workflows/build-wheels-release.yml
    with:
      version: ${{ matrix.version }}
